### Notebook 2.2: Introducing PyTorch

In [61]:
import numpy as np
import torch

PyTorch is very similar to NumPy in its basic functionality.  In PyTorch arrays are called tensors.

In [62]:
a = torch.tensor(5)
a

tensor(5)

In [63]:
b = torch.tensor(6)
a+b

tensor(11)

In [64]:
c = torch.zeros(3,5).float()
c

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

*A note on broadcasting:* You may have noticed in the previous lab that NumPy is particular about the sizes of the arrays in operations; PyTorch is the same way.

For example, if `A` has shape `(10,5)` and `b` has shape `(10,)`, then we can't compute `A*b`.  It wants the *last* dimensions to match, not the first ones.

In [65]:
A = torch.randn(size=(10,5))
b = torch.ones(10)

In [66]:
try:
    A*b
except RuntimeError as e:
    print(e)

The size of tensor a (5) must match the size of tensor b (10) at non-singleton dimension 1


If we add a dimension to the end of `b` with size one, then we can broadcast the multiplication across the last dimension.

In [67]:
A*b[:,None]

tensor([[-1.5450,  0.6478,  0.4382, -0.0085,  0.4253],
        [-0.2660, -0.0405,  1.0477, -0.1232, -1.9797],
        [ 0.1212,  0.5171,  0.8610,  0.3446,  0.3235],
        [-1.0915, -0.0723,  1.1852,  0.9968,  0.4385],
        [ 1.2980,  0.6334,  0.1518, -2.5855, -0.4267],
        [ 1.0543, -0.4393,  0.1511,  0.6703, -0.5096],
        [ 0.6533,  0.0480,  0.0119, -0.5000, -0.6770],
        [-0.4903, -1.7735,  0.5487,  1.1832,  0.7086],
        [-1.3067, -0.5347, -0.6986, -0.0903, -0.9602],
        [ 1.0316, -0.1981, -0.0930,  0.1594,  0.8016]])

In [68]:
A*b.unsqueeze(-1)

tensor([[-1.5450,  0.6478,  0.4382, -0.0085,  0.4253],
        [-0.2660, -0.0405,  1.0477, -0.1232, -1.9797],
        [ 0.1212,  0.5171,  0.8610,  0.3446,  0.3235],
        [-1.0915, -0.0723,  1.1852,  0.9968,  0.4385],
        [ 1.2980,  0.6334,  0.1518, -2.5855, -0.4267],
        [ 1.0543, -0.4393,  0.1511,  0.6703, -0.5096],
        [ 0.6533,  0.0480,  0.0119, -0.5000, -0.6770],
        [-0.4903, -1.7735,  0.5487,  1.1832,  0.7086],
        [-1.3067, -0.5347, -0.6986, -0.0903, -0.9602],
        [ 1.0316, -0.1981, -0.0930,  0.1594,  0.8016]])

In general, carefully check the sizes of all arrays in your code!