### Lab 1.1: Introduction to Python Notebooks and NumPy

In [ ]:
!pip install -q -r https://raw.githubusercontent.com/calpoly-data4620/DATA-4620-Labs/refs/heads/main/requirements.txt

#### How to use a Python notebook

* `Shift-Enter` to run the current cell and move to the next one
* `Ctl-Enter` to run the current cell *without* moving to the next one
* You can add code or text cells
* The result of the last line in each block will be printed out, unless it is an assignment

Remember -- your variables persist as you move between cells!  Be careful about moving backward in the code -- you might enter an unexpected state where your variables are not initialized properly.  If you are seeing strange code behavior, try restarting the kernel and running the notebook again.

When you run a cell, it will print the output of the last line if it is not an assignment.

In [1]:
a = 10

a

10

In [2]:
a + 2

12

NumPy is the main Python package for working with vectors and matrices, or more generally, arrays.  Typically you import it as `np`:

In [4]:
import numpy as np

There are many to ways to create arrays.  For example, you can convert a Python list to a NumPy array:

In [5]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

The syntax for accessing list elements is similar to Python slicing:

In [6]:
a[0]

np.int64(1)

In [7]:
a[:3]

array([1, 2, 3])

In [8]:
a[::2]

array([1, 3, 5])

In [9]:
a[[0,2,4]]

array([1, 3, 5])

You can think of a matrix as a list of lists.

In [10]:
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

Here `b` is a list of two lists of three elements.  This is a matrix of two rows and three columns, as we can see by checking the `shape` of the array.

In [11]:
b.shape

(2, 3)

The first axis has size 2, and the second axis has size 3.

Now when we use slicing, we will obtain entire rows:

In [12]:
b[0]

array([0, 1, 2])

In [13]:
b[1]

array([3, 4, 5])

To access a column, we need to use `:` in the first axis, to indicate that we want to take all elements along that axis, and then indicate the column number for the second axis.

In [14]:
b[:,0]

array([0, 3])

In [15]:
b[:,1]

array([1, 4])

In [16]:
b[:,2]

array([2, 5])

Note that when we access a single column, it is returned as a list with a single axis.

In [17]:
b[:,0].shape

(2,)

When you ask for multiple indices in both axes, the output will be a two-dimensional matrix.

In [18]:
b[:2,:2]

array([[0, 1],
       [3, 4]])

In [19]:
b[:2,:2].shape

(2, 2)

We can of course have more than two axes.  For example, we can have a list of list of lists, meaning an array with three axes.

In [20]:
c = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [21]:
c.shape

(2, 2, 3)

We can think of this array as list of two $2\times3$ arrays.

The great thing about NumPy is that you can easily perform mathematical operations on the entire array without needing to use for loops.

In [22]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
b+2

array([[2, 3, 4],
       [5, 6, 7]])

In [24]:
b+2*b

array([[ 0,  3,  6],
       [ 9, 12, 15]])

NumPy has lots of math functions which can operate on arrays.

In [25]:
np.sin(b)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427]])

In [26]:
np.pow(b,2)

array([[ 0,  1,  4],
       [ 9, 16, 25]])

# Exercises

1. Create a $3\times5$ array of zeros using a NumPy function.

*Hint: check the [NumPy documentation](https://numpy.org/doc/stable/reference/index.html#reference).*

2. Create an $1\times3$ array of ones using a NumPy function.

3. Construct a matrix like this:

$$
\begin{bmatrix}
1 & 1 & 1\\
2 & 2 & 2\\
3 & 3 & 3\\
4 & 4 & 4
\end{bmatrix}
$$

using NumPy functions `arange` and `stack`.

4. Using the matrix you made in Question 3, access:

* the first row
* the third column
* the last two columns
* the bottom-right $2\times2$ submatrix.

4. Use `matplotlib` to plot $sin(x)$ for $x \in [0,2\pi]$.  

*Hints:* 
* Use `np.linspace` to make a range of values from 0 to $2\pi$.
* Do `from matplotlib import pyplot as plt` and use `plt.plot()`.